In [1]:
import pandas as pd
import numpy as np

In [44]:
df= pd.read_csv("nfts_train_withopenrarity.csv")

In [45]:
df.head(20)

,global_index,nft_id,collection_id,rarity_score,openrarity_score,openrarity_rank,openrarity_max_rank,last_sale_date,last_sale_price,total_supply,...,n_tweets_in_range,avg_likes,avg_replies,avg_retweets,min_likes,min_replies,min_retweets,max_likes,max_replies,max_retweets
0,41509,0,54,586.637392,0.986535,5814,9928,2022-03,0.046583,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
1,41510,1,54,737.552774,1.003833,4386,9928,2022-06,0.026642,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
2,41511,2,54,541.351029,0.977299,6549,9928,2022-06,0.035053,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
3,41512,3,54,653.061839,1.015803,3497,9928,2022-01,0.053752,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
4,41513,4,54,732.183875,0.997331,4926,9928,2022-05,0.030615,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
5,41514,5,54,586.878197,0.997141,4937,9928,2022-01,0.047204,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
6,41515,6,54,561.616909,1.002317,4506,9928,2022-01,0.003725,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
7,41516,7,54,570.188083,0.982352,6125,9928,2022-01,0.048103,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
8,41517,8,54,586.759661,0.977011,6574,9928,2022-06,0.036912,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
9,41518,9,54,628.812422,0.950394,8328,9928,2022-05,0.028007,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
10,41519,10,54,625.653369,1.001502,4570,9928,2022-05,0.005713,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
11,41520,11,54,390.611802,0.886513,9878,9928,2021-12,0.044708,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
12,41521,12,54,512.811855,0.951168,8285,9928,2021-12,0.008863,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
13,41522,13,54,630.066260,1.011422,3822,9928,2021-12,0.038866,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
14,41523,14,54,1181.985416,1.058641,1273,9928,2021-12,0.002738,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
15,41524,15,54,718.783064,1.017173,3398,9928,2022-04,0.041796,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
16,41525,16,54,680.171378,1.044468,1822,9928,2022-04,0.009304,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
17,41526,17,54,2774.499818,1.108954,283,9928,2022-04,0.004922,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
18,41527,18,54,762.514506,1.038757,2081,9928,2022-04,0.009380,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54
19,41528,19,54,767.119340,1.043004,1897,9928,2022-04,0.003215,9997,...,19,0.0,0.0,8.947368,0,0,1,0,0,54

In [46]:
df['last_sale_price'].corr(df.total_supply)

-0.2730963160496882

In [47]:
df.shape

(46592, 31)

In [48]:
from sklearn.model_selection import GroupShuffleSplit

groups = df["collection_id"]
gss = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in gss.split(df, groups=groups):
    train_df = df.iloc[train_index]
    test_df = df.iloc[test_index]

In [49]:
train_df.collection_id.value_counts()

58    15555
50     9999
54     9928
34     5555
Name: collection_id, dtype: int64

In [50]:
test_df.collection_id.value_counts()

38    5555
Name: collection_id, dtype: int64

In [51]:
test_df.head()

,global_index,nft_id,collection_id,rarity_score,openrarity_score,openrarity_rank,openrarity_max_rank,last_sale_date,last_sale_price,total_supply,...,n_tweets_in_range,avg_likes,avg_replies,avg_retweets,min_likes,min_replies,min_retweets,max_likes,max_replies,max_retweets
25483,171210,0,38,113.089703,1.020758,1541,5555,2022-07,0.055225,5555,...,4,256.5,45.0,78.0,0,0,24,459,101,135
25484,171211,1,38,138.415342,0.946079,4538,5555,2022-08,0.040194,5555,...,4,256.5,45.0,78.0,0,0,24,459,101,135
25485,171212,2,38,109.507345,1.004859,2097,5555,2022-08,0.018501,5555,...,4,256.5,45.0,78.0,0,0,24,459,101,135
25486,171213,3,38,99.062352,0.977173,3676,5555,2022-08,0.006702,5555,...,4,256.5,45.0,78.0,0,0,24,459,101,135
25487,171214,4,38,68.597548,1.003270,2181,5555,2022-07,0.076658,5555,...,4,256.5,45.0,78.0,0,0,24,459,101,135

In [52]:
test_df.shape

(5555, 31)

In [53]:
train_df.shape

(41037, 31)

In [54]:
xtrain= train_df.drop(columns="last_sale_price")
ytrain= train_df["last_sale_price"]

In [55]:
xtest= test_df.drop(columns="last_sale_price")
ytest= test_df["last_sale_price"]

In [56]:
# changing there data type for object to integer
xtrain['contract_type'] = xtrain['contract_type'].map({'own': 1, 'default': 0})
xtrain['verification_status'] = xtrain['verification_status'].map({'approved': 1, 'verified': 0})
xtest['contract_type'] = xtest['contract_type'].map({'own': 1, 'default': 0})
xtest['verification_status'] = xtest['verification_status'].map({'approved': 1, 'verified': 0})

In [57]:
xtrain.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 41037 entries, 0 to 46591
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   global_index         41037 non-null  int64
 1   nft_id               41037 non-null  int64
 2   collection_id        41037 non-null  int64
 3   rarity_score         41037 non-null  float64
 4   openrarity_score     41037 non-null  float64
 5   openrarity_rank      41037 non-null  int64
 6   openrarity_max_rank  41037 non-null  int64
 7   last_sale_date       41037 non-null  object
 8   total_supply         41037 non-null  int64
 9   creation_date        41037 non-null  object
 10  verification_status  41037 non-null  int64
 11  n_of_traits          41037 non-null  int64
 12  contract_type        41037 non-null  int64
 13  seller_fees          41037 non-null  int64
 14  platform_fees        41037 non-null  int64
 15  openrarity_enabled   41037 non-null  int64
 16  has_website          41037 non-null  int64
 17  has_own_twitter      41037 non-null  int64
 18  has_discord          41037 non-null  int64
 19  has_medium           41037 non-null  int64
 20  n_tweets_in_range    41037 non-null  int64
 21  avg_likes            41037 non-null  float64
 22  avg_replies          41037 non-null  float64
 23  avg_retweets         41037 non-null  float64
 24  min_likes            41037 non-null  int64
 25  min_replies          41037 non-null  int64
 26  min_retweets         41037 non-null  int64
 27  max_likes            41037 non-null  int64
 28  max_replies          41037 non-null  int64
 29  max_retweets         41037 non-null  int64
dtypes: float64(5), int64(23), object(2)
memory usage: 9.7+ MB

In [58]:
xtrain['last_sale_date'] = pd.to_datetime(xtrain['last_sale_date'], format='%Y-%m')
xtest['last_sale_date'] = pd.to_datetime(xtest['last_sale_date'], format='%Y-%m')

In [59]:
xtrain['creation_date'] = pd.to_datetime(xtrain['creation_date'], format='%Y-%m')
xtest['creation_date'] = pd.to_datetime(xtest['creation_date'], format='%Y-%m')

In [60]:
xtrain.last_sale_date.dtype

dtype('<M8[ns]')

In [61]:
xtrain.drop(columns=['last_sale_date', 'creation_date'], inplace=True)
xtest.drop(columns=['last_sale_date', 'creation_date'], inplace=True)

In [62]:
ytrain.head()

0    0.046583
1    0.026642
2    0.035053
3    0.053752
4    0.030615
Name: last_sale_price, dtype: float64

In [63]:
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import RandomizedSearchCV
import time

nn = MLPRegressor(random_state=7, max_iter = 200)

# specify the hyperparameters and their values
# 4 x 3 x 2 = 24 combinations in the grid
param_grid = {
    'hidden_layer_sizes': [(100,)],
    'activation': ['relu'],
    'solver': ['lbfgs', 'adam']
}

# we'll use 5-fold cross-validation
grid_search = RandomizedSearchCV(nn, param_grid, cv=5,
                           scoring='neg_root_mean_squared_error', 
                           return_train_score=True,
                          n_jobs = -1) 

start = time.time()
grid_search.fit(xtrain, ytrain)
nn_time = time.time() - start
print(f"Took {nn_time} seconds")

c:\Users\Gagan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_search.py:305: UserWarning: The total space of parameters 2 is smaller than n_iter=10. Running 2 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Took 49.467708349227905 seconds

c:\Users\Gagan\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:541: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)

In [64]:
nn_train_score = grid_search.best_score_
nn_train_score

-125.9813812766794

In [35]:
import xgboost as xgb

# convert data into DMatrix
dtrain = xgb.DMatrix(xtrain, label=ytrain, enable_categorical = 'True')
dtest = xgb.DMatrix(xtest, label=ytest, enable_categorical = 'True')

# define the parameters for XGBoost
params = {'objective': 'reg:squarederror', # regression objective
          'eval_metric': 'rmse', # evaluation metric
          'eta': 0.01, # learning rate
          'max_depth': 10, # maximum depth of the tree
          'subsample': 0.8, # subsample ratio
          'colsample_bytree': 0.8# column sample by tree ratio
         }

# train the model using the defined parameters
xg_reg = xgb.train(params, dtrain, num_boost_round=1000, enable_categorical = True)

ValueError: DataFrame.dtypes for data must be int, float, bool or category. When categorical type is supplied, The experimental DMatrix parameter`enable_categorical` must be set to `True`.  Invalid columns:last_sale_date: datetime64[ns], creation_date: datetime64[ns]

In [24]:
# predict on the test set
y_pred = xg_reg.predict(dtest)

In [25]:
# calculate the root mean squared error
from sklearn.metrics import mean_squared_error
rmse = np.exp(-mean_squared_error(ytest, y_pred, squared=False)/10)
print("Root Mean Squared Error: ", rmse)

Root Mean Squared Error:  0.938943088930439

In [26]:
pip install open_rarity

Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
ERROR: Could not find a version that satisfies the requirement open_rarity (from versions: none)
ERROR: No matching distribution found for open_rarity
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -ikit-learn (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution - (c:\programdata\anaconda3\lib\site-packages)
WARNING: Ignoring invalid distribution -cikit-learn (c:\programdata\anaconda3\lib\site-packages)

In [5]:
# OpenRarity version 0.4.0-beta
from open_rarity import (
    Collection,
    Token,
    RarityRanker,
    TokenMetadata,
    StringAttribute,
)
from open_rarity.models.token_identifier import EVMContractTokenIdentifier
from open_rarity.models.token_standard import TokenStandard

# Create OpenRarity collection object and provide all metadata information
collection = Collection(
    name="My Collection Name",
    attributes_frequency_counts={
        "hat": {"cap": 1, "visor": 2},
        "shirt": {"blue": 2, "green": 1},
    },
    tokens=[
        Token(
            token_identifier=EVMContractTokenIdentifier(
                contract_address="0xa3049...", token_id=1
            ),
            token_standard=TokenStandard.ERC721,
            metadata=TokenMetadata(
                string_attributes={
                    "hat": StringAttribute(name="hat", value="cap"),
                    "shirt": StringAttribute(name="shirt", value="blue"),
                }
            ),
        ),
    ],
)  # Replace inputs with your collection-specific details here


# Generate scores for a collection
ranked_tokens = RarityRanker.rank_collection(collection=collection)

# Iterate over the ranked and sorted tokens
for token_rarity in ranked_tokens:
    token_id = token_rarity.token.token_identifier.token_id
    rank = token_rarity.rank
    score = token_rarity.score
    print(f"\tToken {token_id} has rank {rank} score: {score}")

	Token 1 has rank 1 score: -0.0

C:\Users\Gagan\AppData\Local\Temp\ipykernel_35780\2198647050.py:13: DeprecationWarning: `attribute_frequency_counts` is deprecated and will be removed. Counts will be derived from the token data.
  collection = Collection(